# Generated by Django 4.1.5 on 2023-01-15 05:38

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highest_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(auctions.models.delete_function_for_highest_bid), related_name='highest_of', to='auctions.bid'),
        ),
    ]
